import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="flex justify-between items-center border-b border-black dark:bg-white px-5 py-3 text-sm">
            <div className="flex gap-5 items-center">
              <img src="./vercel.svg" alt="" className="aspect-square w-5" />
              <div>Vision Craft </div>
              <div>Explore</div>
              <div>Learn</div>
            </div>
            <div className="flex gap-5 items-center">
              <div>Login </div>
              <div>Sign Up</div>
            </div>
          </div>
        </div>

        <div>{children}</div>
      </body>
    </html>
  );
}
